# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeTwilioIPMessagingExample' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeTwilioIPMessagingExample
  inherit! :search_paths
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'React', :subspecs => ['Core', 'RCTActionSheet', 'RCTGeolocation', 'RCTImage', 'RCTLinkingIOS', 'RCTNetwork', 'RCTText', 'RCTSettings', 'RCTVibration', 'RCTWebSocket'], :path => '../node_modules/react-native'
  
  source 'https://github.com/twilio/cocoapod-specs'
  pod 'TwilioIPMessagingClient', '~> 0.14.2'

  pod 'RCTTwilioIPMessaging', :path => '../node_modules/react-native-twilio-ip-messaging/ios'


end
