# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RCTTwilioChat' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for RCTTwilioChat
  source 'https://github.com/twilio/cocoapod-specs'
  pod 'TwilioChatClient', '~> 0.17.1'
  pod 'TwilioAccessManager', '~> 0.1.3'
end
